### ISSUE TITLE
The processor's `/status` endpoint returns 200 in all cases

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#107]
The actual status gets set correctly in the body but the response status code is always `200` even in `in_progress` and `failed` cases.

**Comment by kasbah** [comment]
That's intentional. The JSON returns successfully, no http error ocurred, hence `200`. With the `/files/` endpoint it's different because we can't return the requested file, so we return a http error. It's all documented [here](https://github.com/kitspace/kitspace-v2/blob/61fc219afe265635a0dc08da50cbeb0eb2393f7a/processor/README.md#protocol) now.
