### ISSUE TITLE
Make assets path consistent for mutli and normal projects

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/kitspace-v2#149]
For multi projects the asset path is `[user]/[project]/[git-ref]/[multi-project-name]/[asset-name]`.
For normal projects the asset path is `[user]/[project]/[git-ref]/[asset-name]`.

I think it's better to move the `multi-project-name` before the `git-ref`:
```
[user]/[project]/[multi-project-name]/[git-ref]/[asset-name]
```
To make it consistent with the `frontend` naming convention.

**Comment by kasbah** [comment]
What would the practical benefits be exactly? 

I think `[git-ref]/[multi-project-name]` makes more sense because the `[multi-project-name]` can change based on `[git-ref]` i.e. you can change the `[multi-project-name]` in kitspace.yaml and make a new commit. 

I think this would require quite a bit of work in terms of changing how the processor thinks about directories or add some confusing re-directs to be done by the server. I'm reluctant to change this unless there are some clear practical benefits, not just a "would be nice".
